version: 0.2
 
phases:
  build:
    commands:
      - gcc hello-world.c -o hello-world-app
      - tar -xvf hello-world.tar .
      - mv hello-world/* ../
      
artifacts:
  files:
    - '**/*' 
  base-directory: $CODEBUILD_SRC_DIR
  discard-paths: no
